### ISSUE TITLE
Account Callback

### ISSUE THREAD

**Issue by dhruv850** [hellosign/hellosign-embedded-demo#2]
Hey can you please explain to me ? How to setup an API app and establish the callback event.

**Comment by nathanbuchar** [comment]
Hey @dhruv850, sorry for the late reply! This repo isn't often monitored for new issues.

If you're still looking for help, you can find a [Quickstart Guide](https://github.com/hellosign/hellosign-embedded/wiki/Quickstart) over at the main HelloSign Embedded repo. You might also want to check out HelloSign's [API Documentation](app.hellosign.com/api/documentation).

There's also a pretty nifty [HelloSign Embedded testing tool](https://app.hellosign.com/api/embeddedTest) on our website which will allow you to get a sense of how HelloSign Embedded looks and feels. If you have any other questions regarding our API or implementation, feel free to reach out to our API Support team at apisupport@hellosign.com :)
